import jsPDF from "jspdf";
import type { Assumptions } from "./assumptions";
import { simulateCashflow } from "./cashflow";
import { runScenario, deriveCacPayback } from "./forecast";
import { blankPricingStrategy, vwAcceptableRange, type PricingStrategy } from "./pricingStrategy";
import { computeImpliedIrr } from "./impliedIrr";
import { computePlanSummary, type PlanSummary } from "./planSummary";
import { monthCalendar, planStartLabel } from "./dateAnchor";
import { computePlanNarrative, type LinkStatus } from "./planNarrative";
import { computePricingMaturity } from "./pricingMaturity";

const fmtM = (n: number) => n >= 1e9 ? `$${(n / 1e9).toFixed(1)}B` : n >= 1e6 ? `$${(n / 1e6).toFixed(1)}M` : `$${(n / 1e3).toFixed(0)}K`;
const fmtUsd = (v: number) => `$${Math.round(v).toLocaleString("en-US")}`;

export interface ExportCharts {
  forecastImg?: string;
  cashflowImg?: string;
}

export function exportPdf(a: Assumptions, pricingArg?: PricingStrategy, charts?: ExportCharts, summaryArg?: PlanSummary) {
  // Pricing lives on the assumptions store; fall back to blank if not provided.
  const pricing = pricingArg ?? a.pricing ?? blankPricingStrategy();
  const summary = summaryArg ?? computePlanSummary(a);
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();
  const M = 56;
  let y = M;

  const ownership = a.fundraise.dilutionPct / 100;
  const postMoney = ownership > 0 ? a.fundraise.raise / ownership : 0;
  const preMoney = postMoney - a.fundraise.raise;
  const reqReturn = a.fundraise.raise * Math.pow(1 + a.fundraise.targetIrr / 100, a.fundraise.yearsToExit);
  const reqExit = ownership > 0 ? reqReturn / ownership : 0;
  const calcIrr = a.fundraise.yearsToExit > 0 && a.fundraise.targetMoic > 0
    ? (Math.pow(a.fundraise.targetMoic, 1 / a.fundraise.yearsToExit) - 1) * 100 : 0;
  const implied = computeImpliedIrr(a);

  const base = runScenario(a.forecast, "base");
  const cf = simulateCashflow({ ...a.cashflow, fundraiseAmount: a.fundraise.raise, forecast: a.forecast }, 36);

  const ensureRoom = (need: number) => {
    if (y + need > 740) { doc.addPage(); y = M; }
  };
  const title = (t: string) => {
    ensureRoom(40);
    doc.setFont("helvetica", "bold"); doc.setFontSize(16); doc.setTextColor(17, 24, 39);
    doc.text(t, M, y); y += 22;
    doc.setDrawColor(229, 231, 235); doc.line(M, y - 10, W - M, y - 10);
  };
  const row = (label: string, value: string) => {
    ensureRoom(18);
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(107, 114, 128);
    doc.text(label, M, y);
    doc.setFont("helvetica", "bold"); doc.setTextColor(17, 24, 39);
    doc.text(value, W - M, y, { align: "right" });
    y += 16;
  };
  const para = (t: string) => {
    if (!t) return;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(75, 85, 99);
    const lines = doc.splitTextToSize(t, W - M * 2);
    ensureRoom(lines.length * 13 + 6);
    doc.text(lines, M, y); y += lines.length * 13 + 6;
  };
  const subhead = (t: string) => {
    ensureRoom(20);
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(17, 24, 39);
    doc.text(t, M, y); y += 14;
  };
  const labeledBlock = (label: string, value?: string) => {
    if (!value || !value.trim()) return;
    ensureRoom(28);
    doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(107, 114, 128);
    doc.text(label.toUpperCase(), M, y); y += 12;
    para(value);
    y += 2;
  };

  // Cover
  const startLabel = planStartLabel(a.planStartDate);
  const cal = (m: number) => monthCalendar(a.planStartDate, m);
  doc.setFont("helvetica", "bold"); doc.setFontSize(28); doc.setTextColor(17, 24, 39);
  doc.text("Fundraise Plan", M, y); y += 22;
  doc.setFont("helvetica", "normal"); doc.setFontSize(11); doc.setTextColor(99, 102, 241);
  doc.text("Generated by Founders Toolkit · The Founders Corner", M, y); y += 18;
  doc.setFont("helvetica", "normal"); doc.setFontSize(12); doc.setTextColor(107, 114, 128);
  doc.text(`Plan start: ${startLabel}`, M, y); y += 16;
  doc.text(`Generated ${new Date().toLocaleDateString()}`, M, y); y += 24;

  para("This report covers your pricing, revenue forecast, fundraising math, and cashflow runway as configured in the Founders Toolkit.");
  para(`All "month N" references in this report are measured from the plan start month above (${startLabel} = month 0).`);
  y += 10;

  // Plan summary
  doc.addPage(); y = M;
  title("Plan summary");
  para(summary.planSentence);
  y += 8;

  // 3x2 metric grid
  const cols = 3;
  const cellGap = 12;
  const cellW = (W - M * 2 - cellGap * (cols - 1)) / cols;
  const cellH = 60;
  const metrics: { label: string; value: string; sub?: string }[] = [
    {
      label: "RUNWAY TODAY",
      value: summary.runwayMonth !== null ? `${summary.runwayMonth} mo` : `${summary.horizonMonths}+ mo`,
      sub: summary.runwayMonth !== null ? `cash zero ${cal(summary.runwayMonth)}` : "through horizon",
    },
    {
      label: "RAISE BY",
      value: `Month ${summary.monthsUntilRaise}`,
      sub: `${cal(summary.monthsUntilRaise)}${summary.bufferBeforeZero !== null ? ` · ${Math.max(0, summary.bufferBeforeZero)} mo buffer` : ""}`,
    },
    {
      label: "RUNWAY AFTER RAISE",
      value: summary.monthsRunwayAfterRaise !== null ? `${summary.monthsRunwayAfterRaise} mo` : "—",
      sub: `${fmtM(summary.raise)} round`,
    },
    {
      label: `MRR TODAY → YR ${summary.yearsToExit}`,
      value: `${fmtM(summary.startingMRR)} → ${fmtM(summary.endingMRR)}`,
      sub: `${summary.mrrMultiple.toFixed(1)}× growth`,
    },
    {
      label: "REQUIRED GROWTH",
      value: `${summary.requiredMonthlyGrowth.toFixed(2)}%/mo`,
      sub: `you plan ${summary.actualMonthlyGrowth.toFixed(2)}%/mo`,
    },
    {
      label: "IMPLIED EXIT VALUE",
      value: fmtM(summary.impliedExitValue),
      sub: `at ${summary.revenueMultiple}× ARR`,
    },
  ];
  for (let i = 0; i < metrics.length; i++) {
    const col = i % cols;
    const rowIdx = Math.floor(i / cols);
    if (col === 0 && rowIdx > 0) y += cellH + cellGap;
    const x = M + col * (cellW + cellGap);
    const cy = y;
    doc.setDrawColor(229, 231, 235);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x, cy, cellW, cellH, 6, 6, "FD");
    doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(107, 114, 128);
    doc.text(metrics[i].label, x + 10, cy + 14);
    doc.setFont("helvetica", "bold"); doc.setFontSize(15); doc.setTextColor(17, 24, 39);
    doc.text(metrics[i].value, x + 10, cy + 32);
    if (metrics[i].sub) {
      doc.setFont("helvetica", "normal"); doc.setFontSize(8); doc.setTextColor(107, 114, 128);
      doc.text(metrics[i].sub!, x + 10, cy + 48);
    }
  }
  y += cellH + 20;

  // Verdict bar
  const verdictColors: Record<typeof summary.verdict, [number, number, number]> = {
    green: [16, 185, 129],
    amber: [217, 119, 6],
    red: [220, 38, 38],
  };
  const [vr, vg, vb] = verdictColors[summary.verdict];
  ensureRoom(60);
  doc.setDrawColor(vr, vg, vb);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(M, y, W - M * 2, 50, 6, 6, "FD");
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(vr, vg, vb);
  const verdictLabel = summary.verdict === "green" ? "ON TRACK" : summary.verdict === "amber" ? "TIGHT" : "OFF TRACK";
  doc.text(verdictLabel, M + 14, y + 18);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(31, 41, 55);
  const vLines = doc.splitTextToSize(summary.verdictSentence, W - M * 2 - 28);
  doc.text(vLines, M + 14, y + 32);
  y += 60;

  // How the plan connects (narrative)
  doc.addPage(); y = M;
  title("How the plan connects");
  const narrative = computePlanNarrative(a, summary);
  para(narrative.openingSentence);
  y += 4;
  const statusColor: Record<LinkStatus, [number, number, number]> = {
    ok: [16, 185, 129],
    warn: [217, 119, 6],
    fail: [220, 38, 38],
  };
  const statusGlyph: Record<LinkStatus, string> = { ok: "OK", warn: "GAP", fail: "BREAK" };
  narrative.links.forEach((link, idx) => {
    ensureRoom(60);
    const [r, g, b] = statusColor[link.status];
    // Badge
    doc.setFillColor(r, g, b);
    doc.roundedRect(M, y - 10, 44, 16, 3, 3, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(255, 255, 255);
    doc.text(statusGlyph[link.status], M + 22, y + 1, { align: "center" });
    // Title
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(17, 24, 39);
    doc.text(`[${idx + 1}/5] ${link.title}`, M + 54, y);
    y += 16;
    para(link.sentence);
    if (link.detail) {
      doc.setFont("helvetica", "italic"); doc.setFontSize(9); doc.setTextColor(107, 114, 128);
      const dLines = doc.splitTextToSize(link.detail, W - M * 2);
      ensureRoom(dLines.length * 12 + 4);
      doc.text(dLines, M, y);
      y += dLines.length * 12 + 4;
    }
    y += 4;
  });
  ensureRoom(30);
  doc.setFont("helvetica", "bolditalic"); doc.setFontSize(10); doc.setTextColor(31, 41, 55);
  const cLines = doc.splitTextToSize(narrative.closingSentence, W - M * 2);
  doc.text(cLines, M, y);
  y += cLines.length * 13 + 8;

  // Pricing strategy
  doc.addPage(); y = M;
  title("Pricing strategy");
  labeledBlock("Business model", pricing.context.businessModel);
  labeledBlock("Customer segments", pricing.context.segments);
  labeledBlock("Current pricing", pricing.context.currentPricing);
  labeledBlock("Value metric", pricing.valueMetric.name);
  labeledBlock("Why this metric", pricing.valueMetric.rationale);
  if (pricing.models.length) row("Pricing model(s)", pricing.models.join(", "));
  if (pricing.annualDiscountPct?.trim()) row("Annual discount", `${pricing.annualDiscountPct}%`);
  labeledBlock("Model notes", pricing.modelNotes);

  pricing.tiers.forEach((t) => {
    if (!t.name && !t.monthlyPrice && !t.features) return;
    ensureRoom(60);
    subhead(`Tier — ${t.name || "Untitled"}`);
    if (t.job?.trim()) row("Job to be done", t.job);
    if (t.monthlyPrice?.trim()) row("Monthly price", t.monthlyPrice);
    if (t.annualPrice?.trim()) row("Annual price", t.annualPrice);
    if ((t.customersMonth0 || 0) > 0 || (t.newCustomersPerMonth || 0) > 0) {
      row("Customers · new/mo", `${t.customersMonth0 || 0} customers · +${t.newCustomersPerMonth || 0}/mo`);
    }
    labeledBlock("Features", t.features);
  });

  labeledBlock("Anchoring notes", pricing.anchoringNotes);
  labeledBlock("Upgrade triggers", pricing.upgradeTriggers);

  // Willingness to pay (Van Westendorp) — only render if any field is populated.
  const vw = pricing.vanWestendorp;
  if (vw && (vw.tooCheap || vw.cheap || vw.expensive || vw.tooExpensive || vw.sampleSize || vw.notes)) {
    subhead("Willingness to pay (Van Westendorp)");
    if (vw.tooCheap) row("Too cheap", vw.tooCheap);
    if (vw.cheap) row("Cheap", vw.cheap);
    if (vw.expensive) row("Expensive", vw.expensive);
    if (vw.tooExpensive) row("Too expensive", vw.tooExpensive);
    const range = vwAcceptableRange(vw);
    if (range.complete && range.lower !== null && range.upper !== null) {
      row("Acceptable range", `$${range.lower.toLocaleString()} – $${range.upper.toLocaleString()}`);
    }
    if (vw.sampleSize) row("Sample size", vw.sampleSize);
    labeledBlock("WTP notes", vw.notes);
  }

  const maturity = computePricingMaturity(pricing);
  row("Pricing maturity score", `${maturity.score} / ${maturity.total}`);
  para(maturity.verdict);
  y += 6;

  // Fundraising
  title("Fundraising");
  row("Raise amount", fmtM(a.fundraise.raise));
  row("Dilution", `${a.fundraise.dilutionPct}%`);
  row("Pre-money", fmtM(preMoney));
  row("Post-money", fmtM(postMoney));
  row("Target IRR", `${a.fundraise.targetIrr}%`);
  row("Years to exit", `${a.fundraise.yearsToExit} yr`);
  row("Target MOIC", `${a.fundraise.targetMoic}×`);
  row("Required exit value", fmtM(reqExit));
  row("Calculated IRR (MOIC-implied)", `${calcIrr.toFixed(1)}%`);
  row("Forecast-implied IRR", `${implied.impliedIrrPct.toFixed(1)}% (${implied.basis === "revenue" ? `${a.fundraise.revenueMultiple}× ARR` : "ownership-based"})`);
  row("Year-N ARR (projected)", fmtUsd(implied.arrAtExit));
  row("Implied exit value", fmtM(implied.impliedExitValue));
  y += 6;
  if (implied.impliedIrrPct >= a.fundraise.targetIrr) {
    para(`Verdict: Aligned. Your forecast supports ${implied.impliedIrrPct.toFixed(1)}% IRR, above the ${a.fundraise.targetIrr}% investors require.`);
  } else if (calcIrr >= a.fundraise.targetIrr) {
    para(`Verdict: Gap. Your ${a.fundraise.targetMoic}× MOIC claim implies ${calcIrr.toFixed(1)}% IRR, but your forecast only supports ${implied.impliedIrrPct.toFixed(1)}%. Investors will ask what drives the difference.`);
  } else {
    para(`Verdict: Below target. Both MOIC-claimed (${calcIrr.toFixed(1)}%) and forecast-implied (${implied.impliedIrrPct.toFixed(1)}%) IRR fall under the ${a.fundraise.targetIrr}% target.`);
  }
  y += 12;

  // Revenue
  const cacPayback = deriveCacPayback(a.forecast.cac, a.forecast.blendedArpu, a.cashflow.grossMargin);
  const cacPaybackLabel = cacPayback !== null ? `${cacPayback.toFixed(1)} mo` : "—";
  title("Revenue forecast (base case)");
  row("Starting MRR", fmtUsd(a.forecast.startingMRR));
  row("Monthly new bookings", fmtUsd(a.forecast.monthlyNewBookings));
  row("Blended ARPU", `${fmtUsd(a.forecast.blendedArpu)}/mo`);
  row("CAC", fmtUsd(a.forecast.cac));
  row("CAC payback (derived)", cacPaybackLabel);
  row("Growth rate", `${a.forecast.monthlyGrowthRate}%/mo`);
  row("Gross churn", `${a.forecast.monthlyGrossChurnRate}%/mo`);
  row("Expansion", `${a.forecast.monthlyExpansionRate}%/mo`);
  row("Ending MRR (month 36)", fmtUsd(base.endingMRR));
  row("Ending ARR (month 36)", fmtUsd(base.endingARR));
  y += 12;

  // Forecast chart
  if (charts?.forecastImg) {
    const props = doc.getImageProperties(charts.forecastImg);
    const imgW = W - M * 2;
    const imgH = (props.height * imgW) / props.width;
    if (y + imgH > 740) { doc.addPage(); y = M; }
    doc.addImage(charts.forecastImg, "PNG", M, y, imgW, imgH, undefined, "FAST");
    y += imgH + 12;
  }

  // Cashflow
  title("Cashflow & runway");
  row("Starting cash", fmtUsd(a.cashflow.startingCash));
  row("Starting OpEx", `${fmtUsd(a.cashflow.startingBurn)}/mo`);
  row("OpEx growth", `${a.cashflow.opexGrowthRate}%/mo`);
  row("Gross margin", `${a.cashflow.grossMargin}%`);
  row("Fundraise inflow", `${fmtM(a.fundraise.raise)} in mo ${a.cashflow.monthsUntilRaise} (${cal(a.cashflow.monthsUntilRaise)})`);
  row("Runway hits zero", cf.runwayMonth ? `Month ${cf.runwayMonth} (${cal(cf.runwayMonth)})` : "Beyond 36 months");
  row("Runway after raise", cf.monthsRunwayAfterRaise === null ? "—" : `${cf.monthsRunwayAfterRaise} mo`);
  row("CAC payback", cacPaybackLabel);
  row("Break-even", cf.breakEvenMonth ? `Month ${cf.breakEvenMonth} (${cal(cf.breakEvenMonth)})` : "Not within 36 mo");
  row("Burn multiple (Y1)", isFinite(cf.burnMultiple) ? `${cf.burnMultiple.toFixed(1)}×` : "∞");
  y += 12;

  if (charts?.cashflowImg) {
    const props = doc.getImageProperties(charts.cashflowImg);
    const imgW = W - M * 2;
    const imgH = (props.height * imgW) / props.width;
    if (y + imgH > 740) { doc.addPage(); y = M; }
    doc.addImage(charts.cashflowImg, "PNG", M, y, imgW, imgH, undefined, "FAST");
    y += imgH + 12;
  }

  // Footer note
  doc.addPage(); y = M;
  title("Notes");
  para("All figures are illustrative and based on the assumptions you entered. Validate against benchmarks (SaaS Capital, OpenView, Bessemer State of the Cloud) before sharing with investors.");
  para("Export the JSON file from the toolkit to back up your full plan including pricing strategy, and re-import it any time to continue editing.");

  doc.save("founders-toolkit-plan.pdf");
}
